name: Repository Dispatch

on:
  repository_dispatch:
    types: [my-event-type]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - env:
          NAME: ${{ github.event.client_payload.Name }}
          AGE: ${{ github.event.client_payload.Age }}

      - name: Hello World
        run: echo "Hello $NAME, you are $AGE years old."